### ISSUE TITLE
puppet lookup error when key's value has leading colon

### ISSUE THREAD

**Issue by subeditara** [puppetlabs/puppet#9218]
## Describe the Bug
puppet lookup gives error when key's value is ::ff:10.10.10.1

## Expected Behavior
no error expected

## Steps to Reproduce
1. create file /tmp/puppet/hieradata/system.yaml
```
platform::dns::resolv::servers:
 - fd01::1
 - ::ff:10.10.10.1
```

2. create file /etc/puppet/hiera.yaml
```
---
version: 5
hierarchy:
  - name: "yaml"
    datadir: /tmp/puppet/hieradata
    data_hash: yaml_data
    paths:
      - system.yaml
``` 
3. /opt/puppetlabs/bin/puppet lookup --hiera_config /etc/puppet/hiera.yaml platform::dns::resolv::servers

## Environment
 - puppet --version [8.4.0]
 - Platform [Debian 5.10]

wget https://apt.puppet.com/puppet8-release-bulleye.deb
dpkg -i puppet8-release-bulleye.deb
apt-get update
apt-get install puppet-agent
/opt/puppetlabs/bin/puppet --version 
8.4.0

## Additional Context
Error: Could not run: Lookup of key 'platform::dns::resolv::servers' failed: Value for key 'platform::dns::resolv::servers', in hash returned from data_hash function 'yaml_data', when using location '/tmp/puppet/hieradata/system.yaml', has wrong type, expects Puppet::LookupValue, got Array[Any, 2, 2]
